import test from "node:test";
import assert from "node:assert/strict";
import { createTestRequest, getTestRequestProgress, getTestRequestResponse, insertTestRequestResponse } from "../module/utils/test-request-data.mjs";

const target = { targetKey: "Actor.a", actorUuid: "Actor.a", recipientUserIds: ["u"] };
test("cria e normaliza estado versionado", () => { const request = createTestRequest({ targets: [target] }, { id: "r", userId: "gm", now: 1 }); assert.equal(request.version, 1); assert.equal(request.id, "r"); assert.deepEqual(request.responses, []); });
test("insere resposta e calcula progresso", () => { const request = insertTestRequestResponse(createTestRequest({ targets: [target] }), "Actor.a", { total: 10 }); assert.deepEqual(getTestRequestProgress(request), { answered: 1, total: 1 }); });
test("rejeita alvo inexistente e duplicata", () => { const request = createTestRequest({ targets: [target] }); assert.throws(() => insertTestRequestResponse(request, "Actor.x", {})); const answered = insertTestRequestResponse(request, "Actor.a", { total: 10 }); assert.throws(() => insertTestRequestResponse(answered, "Actor.a", { total: 9 })); });
test("substituição preserva histórico e outras respostas", () => { const request = createTestRequest({ targets: [target, { ...target, targetKey: "Actor.b" }], responses: { "Actor.b": { total: 8 } } }); const one = insertTestRequestResponse(request, "Actor.a", { total: 10 }); const two = insertTestRequestResponse(one, "Actor.a", { total: 9 }, { replace: true }); assert.equal(getTestRequestResponse(two, "Actor.a").history[0].total, 10); assert.equal(getTestRequestResponse(two, "Actor.b").total, 8); });
test("respostas usam array para UUID não ser interpretado como caminho pelo Foundry", () => { const request = insertTestRequestResponse(createTestRequest({ targets: [target] }), target.targetKey, { total: 10 }); assert.ok(Array.isArray(request.responses)); assert.deepEqual(request.responses.map(response => response.targetKey), ["Actor.a"]); assert.equal(getTestRequestResponse(request, target.targetKey).total, 10); });
test("migra resposta expandida por uma atualização antiga do Foundry", () => { const request = createTestRequest({ targets: [target], responses: { Actor: { a: { total: 11 } } } }); assert.equal(getTestRequestResponse(request, target.targetKey).total, 11); assert.deepEqual(getTestRequestProgress(request), { answered: 1, total: 1 }); });